spring:
  datasource:
    password: your_postgres_password

  mail:
    username: your_email@gmail.com
    password: your_gmail_app_password

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: your_google_client_id
            client-secret: your_google_client_secret

jwt:
  secret: your_long_random_jwt_secret
