import { chromium } from 'playwright';
import fs from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
const root = path.resolve(import.meta.dirname, '../..');
const out = path.join(root, 'docs/component4/screenshots');
await fs.mkdir(out, {recursive:true});
const credentials = JSON.parse(await fs.readFile(path.join(root,'backend/target/demo-session.json'),'utf8'));
const api = async (route, token, data) => {
 const r = await fetch('http://127.0.0.1:8081'+route,{method:data?'POST':'GET',headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},...(data?{body:JSON.stringify(data)}:{})});
 if(!r.ok) throw Error(route+' '+r.status+' '+await r.text());
 const text=await r.text();return text?JSON.parse(text):null;
};
const guideSession=await api('/api/auth/login',null,{identifier:'demo_kamal',password:credentials.password});
for(const old of await api('/api/guide-bookings',guideSession.accessToken)) {
 if(['HELD','CONFIRMED','EN_ROUTE','ARRIVED'].includes(old.state)) await api(`/api/guide-bookings/${old.id}/state`,guideSession.accessToken,{state:'CANCELLED'});
 if(old.state==='IN_PROGRESS') await api(`/api/guide-bookings/${old.id}/state`,guideSession.accessToken,{state:'COMPLETED'});
}
const start=new Date(Date.now()+30*60000);start.setUTCSeconds(0,0);
await api('/api/guide-bookings/management/windows',guideSession.accessToken,{startsAt:start.toISOString(),endsAt:new Date(start.getTime()+3*3600000).toISOString()});
const browser = await chromium.launch({channel:'chrome',headless:true});
try {
const semantics = async p => {
 await Promise.race([p.locator('flt-semantics-placeholder').waitFor({state:'attached',timeout:60000}),p.getByRole('button').first().waitFor({timeout:60000})]);
 if(await p.locator('flt-semantics-placeholder').count()) await p.locator('flt-semantics-placeholder').evaluate(el=>el.click());
};
const ctx = await browser.newContext({viewport:{width:390,height:844}});
const page = await ctx.newPage();
page.on('pageerror',e=>console.log('PAGE ERROR:',e.message));
await page.goto('http://127.0.0.1:8085');
await page.locator('flt-glass-pane').waitFor({state:'attached',timeout:60000});
await semantics(page);
await page.getByRole('button',{name:'Start',exact:true}).click();
await page.getByRole('textbox').nth(0).click();
await page.keyboard.type('demo_traveler',{delay:25});
await page.getByRole('textbox').nth(1).click();
await page.keyboard.type(credentials.password,{delay:15});
await page.getByRole('button',{name:'Sign in',exact:true}).click();
await page.waitForTimeout(1500);
await page.getByRole('button',{name:'Profile Profile',exact:true}).click();
await page.waitForTimeout(500);
await page.getByRole('button',{name:'Find guides Approved local guides',exact:true}).click();
await page.waitForTimeout(1200);
await page.screenshot({path:path.join(out,'01-find-guide.png')});
await page.getByRole('button',{name:/Select Guide/}).first().click();
await page.waitForTimeout(700);
await page.getByRole('checkbox',{name:/^\d\d:\d\d$/}).first().click();
await page.getByRole('button',{name:'More visitors',exact:true}).click({clickCount:2,delay:150});
await page.screenshot({path:path.join(out,'02-customize-visit.png')});
await page.getByRole('button',{name:'Review booking details',exact:true}).click();
await page.waitForTimeout(300);
await page.screenshot({path:path.join(out,'03-meeting-location.png')});
await page.getByRole('button',{name:/Confirm Meeting Point/}).click();
await page.waitForTimeout(700);
await page.screenshot({path:path.join(out,'04-review-pay.png')});
await page.getByRole('button',{name:/Pay Now/}).click();
await page.getByRole('button',{name:'SUCCESS',exact:true}).click();
await page.waitForTimeout(700);
const guideContext=await browser.newContext({viewport:{width:390,height:844},permissions:['geolocation'],geolocation:{latitude:6.0305,longitude:80.2168}});
const guidePage=await guideContext.newPage();
await guidePage.goto('http://127.0.0.1:8085');
await semantics(guidePage);
await guidePage.getByRole('button',{name:'Start',exact:true}).click();
await guidePage.getByRole('textbox').nth(0).click();await guidePage.keyboard.type('demo_kamal',{delay:20});
await guidePage.getByRole('textbox').nth(1).click();await guidePage.keyboard.type(credentials.password,{delay:15});
await guidePage.getByRole('button',{name:'Sign in',exact:true}).click();
await guidePage.getByRole('button',{name:'Guide bookings & availability',exact:true}).click();
await guidePage.waitForTimeout(500);
const ownBookings=await api('/api/guide-bookings',guideSession.accessToken);
const currentIndex=ownBookings.findIndex(b=>b.state==='CONFIRMED');
assert(currentIndex>=0);
await guidePage.getByRole('button',{name:'Open booking',exact:true}).nth(currentIndex).click();
await guidePage.getByRole('button',{name:'Set en route',exact:true}).click();
await guidePage.waitForTimeout(500);
await guidePage.getByRole('switch',{name:/Share foreground location/}).click();
await page.waitForTimeout(12000);
let active=(await api('/api/guide-bookings',guideSession.accessToken)).find(b=>b.state==='EN_ROUTE');
assert(active?.locationUpdatedAt,'Guide browser must publish a location');
assert.match(await page.locator('body').ariaSnapshot(),/MINS/);
await page.screenshot({path:path.join(out,'05-guide-tracker.png')});
await guidePage.getByRole('button',{name:'Set arrived',exact:true}).click();
await guidePage.waitForTimeout(500);
active=await api(`/api/guide-bookings/${active.id}`,guideSession.accessToken);
await ctx.setOffline(true);await guideContext.setOffline(true);
await page.waitForTimeout(32000);
assert.match(await page.locator('body').ariaSnapshot(),/OFFLINE/);
await page.screenshot({path:path.join(out,'06-offline-tracker.png')});
await guidePage.mouse.move(180,650);
await guidePage.mouse.wheel(0,800);
await guidePage.waitForTimeout(700);
await guidePage.getByRole('textbox',{name:/Traveler meeting code/}).click();
await guidePage.keyboard.type(active.meetingPin,{delay:70});
await guidePage.getByRole('button',{name:'Compare offline (provisional)',exact:true}).click();
assert.match(await guidePage.locator('body').ariaSnapshot(),/Provisional offline match saved/);
await ctx.setOffline(false);await guideContext.setOffline(false);
await page.waitForTimeout(12000);
const reconciled=await api(`/api/guide-bookings/${active.id}`,guideSession.accessToken);
assert.equal(reconciled.pinUsed,true);
await guidePage.getByRole('button',{name:'Start visit',exact:true}).click();
await guidePage.getByRole('button',{name:'Complete visit',exact:true}).click();
for(let attempt=0;attempt<20;attempt++) {
 const completed=await api(`/api/guide-bookings/${active.id}`,guideSession.accessToken);
 if(completed.state==='COMPLETED') break;
 await page.waitForTimeout(500);
}
assert.equal((await api(`/api/guide-bookings/${active.id}`,guideSession.accessToken)).state,'COMPLETED');
await page.reload();await semantics(page);
await page.getByRole('button',{name:'Profile Profile',exact:true}).click();
await page.getByRole('button',{name:'Find guides Approved local guides',exact:true}).click();
await page.getByRole('button',{name:'My guide bookings',exact:true}).click();
await page.getByRole('group',{name:new RegExp(active.reference)}).last().waitFor({timeout:20000});
assert.match(await page.locator('body').ariaSnapshot(),new RegExp(active.reference));
assert.match(await page.locator('body').ariaSnapshot(),/COMPLETED/);
await fs.writeFile(path.join(out,'browser-results.json'),JSON.stringify({executedAt:new Date().toISOString(),viewport:'390x844',login:'traveler and guide via UI',booking:'3 visitors, LKR 7500, demo payment',tracking:'guide UI publishes browser geolocation fixture; traveler polls',offline:'both contexts offline; cached code compared provisionally; reconnected verification succeeded',completion:'guide UI completed booking',restart:'traveler reload restored session and booking history',physicalGpsTested:false},null,2));
console.log('PASS: traveler booking, separate guide session, foreground location fixture, offline PIN reconciliation, completion and reload recovery.');
} finally { await browser.close(); }
